In [2]:
import numpy as np

# Exercice 1:

In [ ]:
x # Math, Physique, SVT

In [3]:
x = np.random.randint(15, size=(5, 3))
x

array([[ 0, 13,  5],
       [ 5,  8,  2],
       [ 3,  7, 12],
       [ 2,  8,  0],
       [ 7,  4,  1]])

x représente les notes de 5 étudiants en Maths, physique et biologie

* Combien de notes sont supérieur à 5 ?
* Quel est le nombre de notes supérieur à 8 pour chaque étudiants ?
* Quel est le nombre d'élèves ayant au moins 2 notes supérieures à 8 ?
* Est-ce que tous les élèves ont une note supérieur à 3 ?
* Est-ce qu'il y au moins un élève ayant au moins une note supérieur à 12 ?
* Quelle est la moyenne en Math et Physique de la classe si on considère uniquement les  3 élèves dont les notes apparaissent en premier ?
* Combien d'élèves ont au moins 2 notes supérieurs à la médiane des  moyennes (élèves) de la classe ?

# Solution 1 :

Le nombre de notes supérieur 5

In [ ]:
x > 5

array([[ True, False,  True],
       [ True, False, False],
       [False, False, False],
       [False,  True,  True],
       [False,  True,  True]])

In [ ]:
np.sum(x>5)

7

In [ ]:
np.count_nonzero(x>5)

7

Le nombre des notes supérieur à  8 pour chaque élève ?

In [ ]:
x

array([[11,  2, 10],
       [10,  2,  5],
       [ 3,  3,  1],
       [ 2,  9,  9],
       [ 5,  7, 11]])

In [ ]:
y = np.sum(x > 8, axis=1)
y

array([2, 1, 0, 2, 1])

Le nombre d'élèves ayant au moins 2 notes supérieures à 8 ?



In [ ]:
y >= 2

array([ True, False, False,  True, False])

In [ ]:
np.sum(y >= 2)

2

Est-ce que tous les élèves ont une note supérieur à 3 ?

In [ ]:
x > 3

array([[ True, False,  True],
       [ True, False,  True],
       [False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.all( x > 3)

False

In [ ]:
np.all( x > 0)

True

Est-ce qu'il y a un élève dont la note est supérieur à 12

In [ ]:
 x > 12

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
np.any(x > 12)

False

In [ ]:
np.any(x > 10)

True

In [ ]:
x # Math, Physique, SVT

array([[11,  2, 10],
       [10,  2,  5],
       [ 3,  3,  1],
       [ 2,  9,  9],
       [ 5,  7, 11]])

Quelle est la moyenne en Math et Physique de la classe si on considère uniquement les  3 élèves dont les notes apparaissent en premier ?

In [ ]:
np.mean(x[0:3, 0:2 ], axis=0)

array([8.        , 2.33333333])

In [ ]:
x # Math, Physique, SVT

array([[11,  2, 10],
       [10,  2,  5],
       [ 3,  3,  1],
       [ 2,  9,  9],
       [ 5,  7, 11]])

Combien d'élèves ont au moins 2 notes supérieurs à la médiane des  moyennes (élèves) de la classe ?

In [ ]:
y = np.mean(x, axis=1)
y

array([7.66666667, 5.66666667, 2.33333333, 6.66666667, 7.66666667])

In [ ]:
mediane = np.median(y)
mediane

6.666666666666667

In [ ]:
x > mediane

array([[ True, False,  True],
       [ True, False, False],
       [False, False, False],
       [False,  True,  True],
       [False,  True,  True]])

In [ ]:
n = np.sum(x > mediane, axis = 1)
n

array([2, 1, 0, 2, 2])

In [ ]:
np.sum(n >= 2)

3

* Creer un tableau aléatoire de shape (3, 5)
* Modifier le shape à (5, 3)
* Est-ce que c'est possible de modifier le shape à (4, 5)
Creer un tableau qui contient les valeurs de 1 à 9 avec np.arange et donner lui un shape de (3, 3)
* Faites la somme des 2 tableaux
* Choisi un sous tableau aléatoire et extrait le
