In [ ]:
import numpy as np

# Tableaux Numpy : Les bases

## Comment créer un Tableau Numpy

In [ ]:
[1, 5, 8]

In [ ]:
[  3 , 2, 5
   1 , 7, 9
   5 , 9, 6
 
]

In [ ]:
np.array([])

array([], dtype=float64)

In [ ]:
data_un = np.array([[8,9,6]])

In [ ]:
data_deux = np.array([
          [3 , 2, 5],
          [1 , 7, 9],
          [5 , 9, 6]
          ])

In [ ]:
data_deux

array([[3, 2, 5],
       [1, 7, 9],
       [5, 9, 6]])

In [ ]:
data = np.array([[1,4,5]])

In [ ]:
data

array([[1, 4, 5]])

## Les attributs d'un tableau numpy

In [ ]:
data.dtype

dtype('int64')

In [ ]:
data_deux.dtype

dtype('int64')

In [ ]:
np.array([['python', 1]])

array([['python', '1']], dtype='<U6')

In [ ]:
np.array([[1, 5.2]])

array([[1. , 5.2]])

In [ ]:
np.array([[1, 5.2]]).dtype

dtype('float64')

In [ ]:
data_un.ndim

2

In [ ]:
data_un.shape

In [ ]:
np.array([1, 5, 9]).ndim

1

In [ ]:
np.array([1, 5, 9]).shape

(3,)

In [ ]:
data_deux.shape

(3, 3)

In [ ]:
data_deux.ndim

2

In [ ]:
data_deux.size

9

In [ ]:
data_deux.nbytes

72

In [ ]:

          [3 , 2, 5],
          [1 , 7, 9],
          [5 , 9, 6]
          

In [ ]:
data_trois = np.array([
                        [[3 , 2, 5],
                        [1 , 7, 9],
                        [5 , 9, 6]],
                      
                        [[1 , 8, 5],
                        [1 , 5, 9],
                        [5 , 9, 6]],
                      
                      [[3 , 2, 4],
                      [1 , 7, 6],
                      [5 , 9, 6]]

          ])

In [ ]:
data_trois.ndim

3

In [ ]:
data_trois.shape

In [ ]:
# liste d'éléments = vecteur dim 1
# liste de vecteurs =  matrices dim 2
# liste de matrices = cube, tableau de dim 3

In [ ]:
np.array([1,5,9])

array([1, 5, 9])

In [ ]:
np.array([1,5,9]).size

3

In [ ]:
np.array([1,5,9]).ndim

1

In [ ]:
np.array([1,5,9]).shape

(3,)

In [ ]:
np.array([
    [1, 5, 9],
    [8, 9, 7]
])

array([[1, 5, 9],
       [8, 9, 7]])

In [ ]:
np.array([
    [1, 5, 9],
    [8, 9, 7]
]).ndim

2

In [ ]:
np.array([
    [1, 5, 9],
    [8, 9, 7]
]).size

6

In [ ]:
np.array([
    [1, 5, 9],
    [8, 9, 7]
]).shape
# (2 , 3)

(2, 3)

In [ ]:
np.array([
    [1, 5, 9]
]).shape
# (1 , 3)

(1, 3)

In [ ]:
np.array([
    [1, 5, 9]
]).ndim

2

In [ ]:
np.array([
    [1, 5, 9],
    [8, 9, 7]
])

In [ ]:
np.array([
      [ [1, 5, 9],
       [8, 9, 7]  ],  

       [ [2, 5, 9],
       [8, 9, 7]  ],

       [ [13, 5, 9],
       [8, 9, 7]  ]  
])

In [ ]:
np.array([
      [ [1, 5, 9],
       [8, 9, 7]  ],  

       [ [2, 5, 9],
       [8, 9, 7]  ],

       [ [13, 5, 9],
       [8, 9, 7]  ]  
]).ndim

3

In [ ]:
np.array([
      [ [1, 5, 9],
       [8, 9, 7]  ],  

       [ [2, 5, 9],
       [8, 9, 7]  ],

       [ [13, 5, 9],
       [8, 9, 7]  ]  
]).size

18

In [ ]:
np.array([
      [ [1, 5, 9],
       [8, 9, 7]  ],  

       [ [2, 5, 9],
       [8, 9, 7]  ],

       [ [13, 5, 9],
       [8, 9, 7]  ]  
]).shape
# (3 , 2, 3)

(3, 2, 3)

In [ ]:
r = np.array([
      [ [1, 5, 9],
       [8, 9, 7]  ],  

       [ [2, 5, 9],
       [8, 9, 7]  ],

       [ [13, 5, 9],
       [8, 9, 7]  ]  
])
r

array([[[ 1,  5,  9],
        [ 8,  9,  7]],

       [[ 2,  5,  9],
        [ 8,  9,  7]],

       [[13,  5,  9],
        [ 8,  9,  7]]])

In [ ]:
r.nbytes

144

In [ ]:
144/1000 #ko ou kiloBytes

0.144

## Accéder à un élément d'un tableau

In [ ]:
v = np.array([1,5,9])

In [ ]:
v[1]

5

In [ ]:
v[1:]

array([5, 9])

In [ ]:
v[-1]

9

In [ ]:
matrice = np.array([
    [1, 5, 9],
    [8, 9, 7]
])

In [ ]:
matrice[1, 1]

9

In [ ]:
matrice[0,2]

9

In [ ]:
matrice[1, 0]

8

In [ ]:
v2 = np.array([
    [1, 5, 9]
])

In [ ]:
v2[0, 1]

5

In [ ]:
cube = np.array([
      [ [1, 5, 9],
       [8, 9, 7]  ],  

       [ [2, 5, 9],
       [8, 9, 7]  ],

       [ [13, 5, 9],
       [8, 9, 7]  ]  
])

In [ ]:
cube

array([[[ 1,  5,  9],
        [ 8,  9,  7]],

       [[ 2,  5,  9],
        [ 8,  9,  7]],

       [[13,  5,  9],
        [ 8,  9,  7]]])

In [ ]:
cube[2, 0, 0 ]

13

In [ ]:
cube[-1, 0, 0]

13

In [ ]:
matrice

array([[1, 5, 9],
       [8, 9, 7]])

## Accéder à des sous-tableaux d'un tableau

In [ ]:
matrice[0, 1: ]

array([5, 9])

In [ ]:
matrice[1, 1: ]

array([9, 7])

In [ ]:
matrice[0: , 1: ]

array([[5, 9],
       [9, 7]])

In [ ]:
matrice[: , 1: ]

array([[5, 9],
       [9, 7]])

In [ ]:
matrice = np.array([
      0  1  2  3  4      
   0 [1, 5, 9, 4, 6],
   1 [8, 9, 7, 5, 0],
   2 [3, 2, 0, 6, 2],
   3 [8, 6, 7, 8, 9]
])

In [ ]:
matrice[2, 3]

6

In [ ]:
matrice[1:, 2:]

array([[7, 5, 0],
       [0, 6, 2],
       [7, 8, 9]])

In [ ]:
matrice[1:3, 2:4]

array([[7, 5],
       [0, 6]])

In [ ]:
matrice.shape

(4, 5)

In [ ]:
matrice[1:3 , 1:3]

array([[9, 7],
       [2, 0]])

In [ ]:
np.array([[9,7],[2,0]])

array([[9, 7],
       [2, 0]])

In [ ]:
cube = np.array([
      [ [1, 5, 9],
        [8, 9, 7]  ],  

       [ [6, 4, 9],
         [8, 1, 7]  ],

       [ [13, 0, 8],
          [8, 9, 7]  ]  
])

In [ ]:
cube[:2, 1:, :2]

array([[[8, 9]],

       [[8, 1]]])

In [ ]:
cube[:, :, 1:]

array([[[5, 9],
        [9, 7]],

       [[4, 9],
        [1, 7]],

       [[0, 8],
        [9, 7]]])

In [ ]:
np.array(5).ndim

0

In [ ]:
np.array(5).shape

()

In [ ]:
matrice = np.array([
           
   [1, 5, 9, 4, 6],
   [8, 9, 7, 0],
   [3, 2, 0, 6, 2],
   [8, 6, 7, 8, 9]
])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [ ]:
matrice = np.array([
        0  1  2  3  4      
   Paul [1, 5, 9, 4, 6],
   Kevin[8, 9, 7, 5, 0],
   radji[3, 2, 0, 6, 2],
   rock [8, 6, 7, 8, 9]
])

In [ ]:
??np.arange

In [ ]:
matrice = np.arange(9).reshape((3,3))

In [ ]:
matrice

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
matrice[0:2, 1:]

array([[1, 2],
       [4, 5]])

In [ ]:
matrice[1: , :2]

array([[3, 4],
       [6, 7]])

## Vue et non copie d'un tableau

In [ ]:
matrice = np.arange(9).reshape((3,3))
matrice

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
matrice[1, -1] = 9

In [ ]:
matrice

array([[0, 1, 2],
       [3, 4, 9],
       [6, 7, 8]])

In [ ]:
data = matrice[:2, :2]

In [ ]:
data

array([[0, 1],
       [3, 4]])

In [ ]:
data[0, 0] = 15

In [ ]:
data

array([[15,  1],
       [ 3,  4]])

In [ ]:
matrice

array([[15,  1,  2],
       [ 3,  4,  9],
       [ 6,  7,  8]])

## Comment copier alors un tableau ?

In [ ]:
data = matrice[:2, :2].copy()

In [ ]:
data

array([[15,  1],
       [ 3,  4]])

In [ ]:
data[0, 0] = 30

In [ ]:
data

array([[30,  1],
       [ 3,  4]])

In [ ]:
matrice

array([[15,  1,  2],
       [ 3,  4,  9],
       [ 6,  7,  8]])

## Modifier la taille d'un tableau

In [ ]:
x = np.random.randint(100, size=(2, 5))
x

array([[ 3, 87,  9, 32, 13],
       [98, 53, 65, 26, 11]])

In [ ]:
x.reshape((5, 2))

array([[ 3, 87],
       [ 9, 32],
       [13, 98],
       [53, 65],
       [26, 11]])

In [ ]:
u = np.array([1,5,6])
u.shape

(3,)

In [ ]:
u.reshape((1,3))

array([[1, 5, 6]])

In [ ]:
u.reshape((3, 1))

array([[1],
       [5],
       [6]])

In [ ]:
u.reshape( (2, 3) )

ValueError: ignored

## Concatener des Tableaux

In [ ]:
u

array([1, 5, 6])

In [ ]:
v = np.array([7, 8, 9])

In [ ]:
np.concatenate([u, v])

array([1, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate([u, u], axis=1)

AxisError: ignored

In [ ]:
tab = np.vstack([u, v])
tab

array([[1, 5, 6],
       [7, 8, 9]])

In [ ]:
np.hstack([u, v])

array([1, 5, 6, 7, 8, 9])

In [ ]:
tab.reshape((3, 2))

array([[1, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np.vstack([tab, tab])

array([[1, 5, 6],
       [7, 8, 9],
       [1, 5, 6],
       [7, 8, 9]])

In [ ]:
np.hstack([tab, tab])

array([[1, 5, 6, 1, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [ ]:
paul = np.array([5, 9, 25])
paul.shape

(3,)

In [ ]:
paul = paul.reshape((1,3))
paul

array([[ 5,  9, 25]])

In [ ]:
np.vstack([paul, paul])

array([[ 5,  9, 25],
       [ 5,  9, 25]])

In [ ]:
np.hstack([paul, paul])

array([[ 5,  9, 25,  5,  9, 25]])

In [ ]:
np.hstack([paul, paul]).shape

(1, 6)

In [ ]:
paul

array([[ 5,  9, 25]])

In [ ]:
paul.shape

(1, 3)

In [ ]:
x = np.random.randint(16, size=(1, 3))
x

array([[ 4, 15, 15]])

In [ ]:
y = np.vstack([paul, x])
y
# (1, 3)
# (1, 3)

array([[ 5,  9, 25],
       [ 4, 15, 15]])

In [ ]:
# (2, 3)
# (1, 3)

In [ ]:
z = np.vstack([y, x])
z

array([[ 5,  9, 25],
       [ 4, 15, 15],
       [ 4, 15, 15]])

In [ ]:
np.hstack([z, z])

array([[ 5,  9, 25,  5,  9, 25],
       [ 4, 15, 15,  4, 15, 15],
       [ 4, 15, 15,  4, 15, 15]])

In [ ]:
z z # (3, 3) (3,3)

# Calcul sur les tableaux avec Numpy 

## Tableau mieux que les listes ?

In [ ]:
nombres = list(range(2, 9))
nombres

[2, 3, 4, 5, 6, 7, 8]

In [ ]:
output = np.empty(len(nombres))

In [ ]:
output

array([2.35071217e-316, 2.07955588e-312, 2.14321575e-312, 6.79038654e-313,
       6.79038653e-313, 1.87422342e+261, 1.26366678e-306])

In [ ]:
for i, n in enumerate(nombres):
  output[i] = 1 / n
output

array([0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
       0.14285714, 0.125     ])

In [ ]:
nombres_tab = np.array(nombres)
nombres_tab

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
1 / nombres_tab

array([0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
       0.14285714, 0.125     ])

In [ ]:
import time

In [ ]:
time.time()

1612994661.8269765

In [ ]:

nombres = list(range(2, 10_000_000))
output = np.empty(len(nombres))
debut = time.time()
for i, n in enumerate(nombres):
  output[i] = 1 / n
fin  = time.time()
print(fin-debut)

2.372166872024536


In [ ]:
import numpy as np
import time

In [ ]:
debut = time.time()
1 / np.arange(2, 10_000_000)
fin  = time.time()
print(fin-debut)

0.07444596290588379


## Vectorisation*

In [ ]:
l = [5, 8, 9]
[n**2 for n in l]

[25, 64, 81]

In [ ]:
np.array(l) ** 2

array([25, 64, 81])

# Aggregation

In [ ]:
l

[5, 8, 9]

In [ ]:
min(l)

5

In [ ]:
np.min(l)

5

In [ ]:
np.array(l).min()

5

In [ ]:
np.random.seed(9)

In [ ]:
np.random.seed(0)
tab = np.random.randint(15, size=(5, 3))
tab

array([[12,  5,  0],
       [ 3, 11,  3],
       [ 7,  9,  3],
       [ 5,  2,  4],
       [ 7,  6,  8]])

In [ ]:
np.min(tab)

0

In [ ]:
tab.min()

0

In [ ]:
np.min(tab, axis= 0)

array([3, 2, 0])

In [ ]:
np.mean(tab, axis= 1)

array([5.66666667, 5.66666667, 6.33333333, 3.66666667, 7.        ])

In [ ]:
notes = np.random.randint(19, size=(10, 3))
notes

array([[12,  1,  6],
       [ 7, 14, 17],
       [ 5, 13,  8],
       [ 9, 16,  5],
       [15, 15,  0],
       [18,  3, 17],
       [14,  7,  0],
       [ 1,  9,  0],
       [10,  3, 11],
       [18,  2,  0]])

In [ ]:
notes.mean(axis=0)
#np.mean(notes, axis=0)

array([10.9,  8.3,  6.4])

In [ ]:
moy_per_student = np.mean(notes, axis=1)
moy_per_student

array([ 6.33333333, 12.66666667,  8.66666667, 10.        , 10.        ,
       12.66666667,  7.        ,  3.33333333,  8.        ,  6.66666667])

In [ ]:
moy_per_student >= 10

array([False,  True, False,  True,  True,  True, False, False, False,
       False])

In [ ]:
np.mean([0, 1, 1, 0])

0.5

In [ ]:
np.sum([0, 1, 1, 0])

2

In [ ]:
np.sum([False,  True, True, False])

2

In [ ]:
np.sum(moy_per_student >= 10)

4

# Diffusion (broadcasting) avec Numpy