In [ ]:
import numpy as np

# Tableaux Numpy : Les bases

## Comment créer un Tableau Numpy

In [ ]:
[  3 , 2, 5
   1 , 7, 9
   5 , 9, 6
 
]

In [ ]:
np.array([])

array([], dtype=float64)

In [ ]:
data_un = np.array([[8,9,6]])

In [ ]:
data_deux = np.array([
          [3 , 2, 5],
          [1 , 7, 9],
          [5 , 9, 6]
          ])

In [ ]:
data_deux

array([[3, 2, 5],
       [1, 7, 9],
       [5, 9, 6]])

In [ ]:
data = np.array([[1,4,5]])

In [ ]:
data

array([[1, 4, 5]])

## Les attributs d'un tableau numpy

In [ ]:
data.dtype

dtype('int64')

In [ ]:
data_deux.dtype

dtype('int64')

In [ ]:
np.array([['python', 1]])

array([['python', '1']], dtype='<U6')

In [ ]:
np.array([[1, 5.2]])

array([[1. , 5.2]])

In [ ]:
np.array([[1, 5.2]]).dtype

dtype('float64')

In [ ]:
data_un.ndim

2

In [ ]:
data_un.shape

In [ ]:
np.array([1, 5, 9]).ndim

1

In [ ]:
np.array([1, 5, 9]).shape

(3,)

In [ ]:
data_deux.shape

(3, 3)

In [ ]:
data_deux.ndim

2

In [ ]:
data_deux.size

9

In [ ]:
data_deux.nbytes

72

In [ ]:

          [3 , 2, 5],
          [1 , 7, 9],
          [5 , 9, 6]
          

In [ ]:
data_trois = np.array([
                        [[3 , 2, 5],
                        [1 , 7, 9],
                        [5 , 9, 6]],
                      
                        [[1 , 8, 5],
                        [1 , 5, 9],
                        [5 , 9, 6]],
                      
                      [[3 , 2, 4],
                      [1 , 7, 6],
                      [5 , 9, 6]]

          ])

In [ ]:
data_trois.ndim

3

In [ ]:
data_trois.shape

In [ ]:
# liste d'éléments = vecteur dim 1
# liste de vecteurs =  matrices dim 2
# liste de matrices = cube, tableau de dim 3

In [ ]:
np.array([1,5,9])

array([1, 5, 9])

In [ ]:
np.array([1,5,9]).size

3

In [ ]:
np.array([1,5,9]).ndim

1

In [ ]:
np.array([1,5,9]).shape

(3,)

In [ ]:
np.array([
    [1, 5, 9],
    [8, 9, 7]
])

array([[1, 5, 9],
       [8, 9, 7]])

In [ ]:
np.array([
    [1, 5, 9],
    [8, 9, 7]
]).ndim

2

In [ ]:
np.array([
    [1, 5, 9],
    [8, 9, 7]
]).size

6

In [ ]:
np.array([
    [1, 5, 9],
    [8, 9, 7]
]).shape
# (2 , 3)

(2, 3)

In [ ]:
np.array([
    [1, 5, 9]
]).shape
# (1 , 3)

(1, 3)

In [ ]:
np.array([
    [1, 5, 9]
]).ndim

2

In [ ]:
np.array([
    [1, 5, 9],
    [8, 9, 7]
])

In [ ]:
np.array([
      [ [1, 5, 9],
       [8, 9, 7]  ],  

       [ [2, 5, 9],
       [8, 9, 7]  ],

       [ [13, 5, 9],
       [8, 9, 7]  ]  
])

In [ ]:
np.array([
      [ [1, 5, 9],
       [8, 9, 7]  ],  

       [ [2, 5, 9],
       [8, 9, 7]  ],

       [ [13, 5, 9],
       [8, 9, 7]  ]  
]).ndim

3

In [ ]:
np.array([
      [ [1, 5, 9],
       [8, 9, 7]  ],  

       [ [2, 5, 9],
       [8, 9, 7]  ],

       [ [13, 5, 9],
       [8, 9, 7]  ]  
]).size

18

In [ ]:
np.array([
      [ [1, 5, 9],
       [8, 9, 7]  ],  

       [ [2, 5, 9],
       [8, 9, 7]  ],

       [ [13, 5, 9],
       [8, 9, 7]  ]  
]).shape
# (3 , 2, 3)

(3, 2, 3)

In [ ]:
r = np.array([
      [ [1, 5, 9],
       [8, 9, 7]  ],  

       [ [2, 5, 9],
       [8, 9, 7]  ],

       [ [13, 5, 9],
       [8, 9, 7]  ]  
])
r

array([[[ 1,  5,  9],
        [ 8,  9,  7]],

       [[ 2,  5,  9],
        [ 8,  9,  7]],

       [[13,  5,  9],
        [ 8,  9,  7]]])

In [ ]:
r.nbytes

144

In [ ]:
144/1000 #ko ou kiloBytes

0.144

## Accéder à un élément d'un tableau

In [ ]:
v = np.array([1,5,9])

In [ ]:
v[1]

5

In [ ]:
v[1:]

array([5, 9])

In [ ]:
v[-1]

9

In [ ]:
matrice = np.array([
    [1, 5, 9],
    [8, 9, 7]
])

In [ ]:
matrice[1, 1]

9

In [ ]:
matrice[0,2]

9

In [ ]:
matrice[1, 0]

8

In [ ]:
v2 = np.array([
    [1, 5, 9]
])

In [ ]:
v2[0, 1]

5

In [ ]:
cube = np.array([
      [ [1, 5, 9],
       [8, 9, 7]  ],  

       [ [2, 5, 9],
       [8, 9, 7]  ],

       [ [13, 5, 9],
       [8, 9, 7]  ]  
])

In [ ]:
cube

array([[[ 1,  5,  9],
        [ 8,  9,  7]],

       [[ 2,  5,  9],
        [ 8,  9,  7]],

       [[13,  5,  9],
        [ 8,  9,  7]]])

In [ ]:
cube[2, 0, 0 ]

13

In [ ]:
cube[-1, 0, 0]

13

In [ ]:
matrice

array([[1, 5, 9],
       [8, 9, 7]])

In [ ]:
matrice[0, 1: ]

array([5, 9])

In [ ]:
matrice[1, 1: ]

array([9, 7])

In [ ]:
matrice[0: , 1: ]

array([[5, 9],
       [9, 7]])

In [ ]:
matrice[: , 1: ]

array([[5, 9],
       [9, 7]])

In [ ]:
matrice = np.array([
      0  1  2  3  4      
   0 [1, 5, 9, 4, 6],
   1 [8, 9, 7, 5, 0],
   2 [3, 2, 0, 6, 2],
   3 [8, 6, 7, 8, 9]
])

In [ ]:
matrice[2, 3]

6

In [ ]:
matrice[1:, 2:]

array([[7, 5, 0],
       [0, 6, 2],
       [7, 8, 9]])

In [ ]:
matrice[1:3, 2:4]

array([[7, 5],
       [0, 6]])

In [ ]:
matrice.shape

(4, 5)

In [ ]:
matrice[1:3 , 1:3]

array([[9, 7],
       [2, 0]])

In [ ]:
np.array([[9,7],[2,0]])

array([[9, 7],
       [2, 0]])

In [ ]:
cube = np.array([
      [ [1, 5, 9],
        [8, 9, 7]  ],  

       [ [6, 4, 9],
         [8, 1, 7]  ],

       [ [13, 0, 8],
          [8, 9, 7]  ]  
])

In [ ]:
cube[:2, 1:, :2]

array([[[8, 9]],

       [[8, 1]]])

In [ ]:
cube[:, :, 1:]

array([[[5, 9],
        [9, 7]],

       [[4, 9],
        [1, 7]],

       [[0, 8],
        [9, 7]]])

In [ ]:
np.array(5).ndim

0

In [ ]:
np.array(5).shape

()

In [ ]:
matrice = np.array([
           
   [1, 5, 9, 4, 6],
   [8, 9, 7, 0],
   [3, 2, 0, 6, 2],
   [8, 6, 7, 8, 9]
])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [ ]:
matrice = np.array([
        0  1  2  3  4      
   Paul [1, 5, 9, 4, 6],
   Kevin[8, 9, 7, 5, 0],
   radji[3, 2, 0, 6, 2],
   rock [8, 6, 7, 8, 9]
])

## Accéder à des sous-tableaux d'un tableau

## Vue et nom copie d'un tableau

## Comment copier alors un tableau ?

## Modifier la taille d'un tableau

## Concatener des Tableaux

# Calcul sur les tableaux avec Numpy 

## Tableau mieux que les listes ?

## Vectorisation*

# Aggregation

# Diffusion (broadcasting) avec Numpy